name: Scrape and Commit Markdown

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'   # daily at 02:00 UTC; change as needed

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: true
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run scraper (force ignore robots)
      env:
        URL: "https://www.anirdesh.com/harililamrut/index.php?kalash=1&vishram=1"
        IGNORE_ROBOTS: "1"
      run: |
        python fetch_to_md.py "$URL" harililamrut_kalash1_vishram1.md

    - name: Commit generated markdown
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add -A
        if git diff --cached --quiet; then
          echo "No changes"
        else
          git commit -m "Automated: update scraped markdown"
          git push origin HEAD:main
        fi
